---
exclude_paths:
 - "*README.md"
 - "eon-docs/**"
 - "eon-example/**"
 - "eon-core/src/copy/eon/polyfill/**"
 - "eon-core/src/meta/eon/eon/require/require.js"
 - "eon-core/tests/**"
 - "eon-ui/tests/**"