language: node_js
node_js:
- lts/*
cache:
  directories:
  - "${HOME}/.npm"
  - node_modules
  - eon-core/node_modules
install:
- npm install
script:
- npm run build
- npm run test
before_deploy:
- npm run release
- cd ${TRAVIS_BUILD_DIR}
deploy:
  provider: releases
  api_key:
    secure: YcHkN+WJ9ICUS8BxfyeVs1RlpnFJ02dZACvCgMC/14mib7OWUwWeDG2bnoTAAdMLO8cxaRcTz6LIdGIv0Rvx/GgO5oMIVp787MaURX2g9JJtxDDzz7ajf3NUqjkeGXqka8OaiC9t2IRROs/ymEdTawCdyMkLiOn/ouE91e/TlYdawfALcsqnEhVQ7v9TddY1Bp5dG/JpeqA3YwSSGmfBETWhFeCzXhYWylthO4tI50ELSdLpHwMLeU8PO/D0LUVSZYDtoIca3TlyzeR0cJEN315voL6QiJERtdY5Yhlpq1ejazDGjZkHqTWVdlahFeaMvKPHCT5qAfARtuCGRBT2uRHxjCq0LbYdDmJdLlKx0idsXgof+QzRP/8VyycmwyEpSdQuTRMf/hK4Lip6Kf0hJ2oU9l5s9/xdU5A4KpWiF0CKBELfCn7FsA+YGJicgOGsLimuoJ3KnZJtOy/vtv/UWbrFToJ55++3iM2fPHdHiQciRU4KeNNvIjg+BcgrZYca5ifQkJSOhnz/OiRZysvRW1jV3sxrI8F95DngqGJXo3WXSQMfjmCT3Va+JaivfmXA7m2ss7Ge7dCBkLfgCaxIyribJVJPtB7E6sg3FrVtGib0EuuGbHj4do69oCrtPe1Nj2CjNj0T8Pb1fEZazgXPEHdApMiaR08GwRz6haaCNLE=
  file: 
    - eon-core/release/eon-core.zip
    - eon-ui/release/eon-ui.zip
  skip_cleanup: true
  on:
    repo: vimlet/eon
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^release-.*$"