language: node_js
node_js:
- lts/*
cache:
  directories:
  - ${HOME}/.npm
  - node_modules
  - eon-core/node_modules
install:
- npm install
script:
- npm run build
- npm run test
before_deploy:
- npm run release
- cd ${TRAVIS_BUILD_DIR}
deploy:
  provider: releases
  api_key:
    secure: J41Dy4nKgp9FHVr5bnd/f/ZmnVZHz0kcZFagQ/VyVV+vb1TYaS54iMBKXF78R8auU8psPR/b2EF5QRyPmWnDpF9QOQcBsHoqdqgZ7qFihH8FDKE9LeOY6VfwOueH5J4U8JNHFyadLiGbIFOv8QOO9aC87GLloC4x5yN+aA1IcwA0/zj4oPv1W5iMzxQ0NpHNRHy73Q7caDk6q/fTSQNc05mKmitaiStbEr6EA7wzB/e9PfQki5R5iNyvwZ4RyBQ4mnlQaB9lCy9kXt2oSHKNCR49DligiGt8pXLbZPJ6AqJcUVvHhweHO4j4tH/BFgnof1e5gcWBFvT94l5yOxxiVFC7l2TDMutyPWy509nwka2z6BhUiTShD5ys1Pph5b09cCv8HfxSqD6JNycPbWWKQsk4ye+sWBOpDTW/F3DMIbNuYxRBIsVvdxIo9UG6MxrN/Jagj/TAUZSZo3tUPWFNmuIUHM3tgY1S3R6Lo/L07d+o1iNVqe3EqCbj6Ze9OCm5HKjmTx9oKk4oMwIP65PWaRHjZpfmfk6A8trwwUllpmiEMvyj/Ekk+k3MybOwhTlvo/bawUpdWl7ih99S1WLWiS7wUrmALA+6SGV0kBC6Aljym+ErQwJP/IIu6B4zHBc0SSeV6qfJ+BJBWMpBJz7pSeNUgone08Ye4nXOXOtrRDU=
  file: eon-core/release/eon-core.zip
  skip_cleanup: true
  on:
    repo: vimlet/eon
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^release-.*$"
